#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i="0"

while [ $i != "10" ]
do
if [ $i == "3" ]
then
		echo bad luck
fi

if [ $i == "7" ]
then
		echo good luck
fi

if [ $i != "3" ] && [ $i != "7" ]
then
		echo Holberton School
fi
i=$((i+1))
done
