#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
h="0"
m="1"

echo "Hour: $h"
h=$((h+1))

while [ $h != "13" ]
do
	if [ $m == "60" ]
	then
		echo "Hour: $h"
		h=$((h+1))
		i=$(("1"))
	else
		echo $m
		i=$((i+1))
	fi
done
