#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
h="0"
m="1"

while [ $h != "13" ]; do
	echo "Hour: $h"
	m=$(("1"))
	while [ $m != 60 ]
	do
		echo $m
		m=$((m+1))
	done
	h=$((h+1))
done
